# Required changes
# - the subpath of your site, e.g. /blog
baseurl: "/"
# - the base hostname & protocol for your site, e.g. http://example.com
url: "https://html2rss.github.io"

permalink: /blog/:year/:title

title: html2rss

description: |
  html2rss brings back RSS. It's an open source project with decentralised
  instances. These instances generate RSS feeds for websites which do not offer
  them.

github_username: "html2rss"

theme: just-the-docs
color_scheme: dark

logo: assets/images/logo.png

aux_links:
  "GitHub":
    - "https://github.com/html2rss"


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/html2rss/html2rss.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"

sass:
  style: compressed
  sass_dir: assets/css/sass

plugins:
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-sitemap
  - jekyll-target-blank

exclude:
  - .git/
  - .github/
  - .gitignore
  - .jekyll-cache/
  - .nvmrc
  - .rubocop.yml
  - .ruby-version
  - .sass-cache/
  - .stylelintrc.json
  - bin/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - Makefile
  - node_modules/
  - package.json
  - vendor
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.error
  - yarn.lock
