---
- domain: adfc.de
  name: pressemitteilungen
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.adfc.de/presse/pressemitteilungen/
    time_zone: Europe/Berlin
    ttl: 720
    language: de
- domain: apnews.com
  name: hub
  valid_channel_url: false
  url_parameters:
    section: &1 !ruby/class 'String'
  default_parameters:
    section: news
  channel:
    url: https://apnews.com/%<section>s
    language: en
    ttl: 120
    time_zone: UTC
- domain: avherald.com
  name: index
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://avherald.com/
    language: en
    ttl: 120
    time_zone: UTC
- domain: bbc.co.uk
  name: available_episodes
  valid_channel_url: false
  url_parameters:
    id: *1
  default_parameters:
    id: b006wkfp
  channel:
    url: https://www.bbc.co.uk/programmes/%<id>s/episodes/player
    time_zone: UTC
    ttl: 720
- domain: bbc.com
  name: mundo
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.bbc.com/mundo
    language: es
    ttl: 360
    time_zone: UTC
- domain: blog.mondediplo.net
  name: feed
  valid_channel_url: false
  url_parameters:
    blog: *1
  default_parameters:
    blog: "-Defense-en-ligne-"
  channel:
    url: https://blog.mondediplo.net/%<blog>s
    time_zone: Europe/Paris
    title: 'blog.mondediplo.net: %<blog>s'
    ttl: 120
- domain: canarianweekly.com
  name: front
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.canarianweekly.com/
    time_zone: Europe/London
    ttl: 720
    language: en
- domain: cinemascore.com
  name: index
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://webapp.cinemascore.com/guest/surveys
    ttl: 720
    json: true
    time_zone: America/Los_Angeles
- domain: cleanenergywire.org
  name: news
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.cleanenergywire.org/news-archive
    time_zone: Europe/Berlin
    ttl: 360
- domain: cnet.com
  name: section_sub
  valid_channel_url: false
  url_parameters:
    section: *1
    sub: *1
  default_parameters:
    section: news
    sub: tech
  channel:
    url: https://www.cnet.com/%<section>s/%<sub>s/
    language: en
    ttl: 360
    time_zone: UTC
- domain: computerbase.de
  name: meistgelesen
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    title: 'computerbase.de: meistgelesen'
    url: https://www.computerbase.de
    time_zone: Europe/Berlin
    ttl: 360
    language: de
- domain: cutle.fish
  name: index
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://cutle.fish/
    ttl: 360
    time_zone: UTC
- domain: deraktionaer.de
  name: meistgelesen
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    title: 'deraktionaer.de: meistgelesen'
    url: https://deraktionaer.de/
    time_zone: Europe/Berlin
    ttl: 360
    language: de
- domain: developer.apple.com
  name: tutorials_data_documentation_technotes_json
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    json: true
    url: https://developer.apple.com/tutorials/data/documentation/Technotes.json
    ttl: 360
    time_zone: UTC
- domain: dfs.de
  name: pressemitteilungen
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.dfs.de/homepage/de/medien/presse/
    time_zone: Europe/Berlin
    ttl: 1440
    language: de
- domain: dsw-info.de
  name: presse
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.dsw-info.de/presse
    time_zone: Europe/Berlin
    ttl: 720
    language: de
- domain: espn.com
  name: f1
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.espn.com/f1/
    time_zone: UTC
    ttl: 60
- domain: fia.com
  name: documents
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.fia.com/documents/championships/fia-formula-one-world-championship-14/season/season-2025-2071
    ttl: 360
    time_zone: UTC
- domain: formula1.com
  name: latest
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.formula1.com/en/latest/all.html
    time_zone: UTC
    ttl: 120
- domain: github.com
  name: releases
  valid_channel_url: false
  url_parameters:
    username: *1
    repository: *1
  default_parameters:
    username: nuxt
    repository: nuxt.js
  channel:
    url: https://github.com/%<username>s/%<repository>s/releases
    time_zone: UTC
    ttl: 720
    description: Releases of %<username>s/%<repository>s on github.com.
- domain: iaapa.org
  name: news
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.iaapa.org/news
    time_zone: UTC
    ttl: 720
- domain: imdb.com
  name: ratings
  valid_channel_url: false
  url_parameters:
    user_id: *1
  default_parameters:
    user_id: ur7019649
  channel:
    url: https://www.imdb.com/user/%<user_id>s/ratings
    time_zone: UTC
    ttl: 1440
- domain: ingenieur.de
  name: karriere_arbeitsleben_heiko_mell
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.ingenieur.de/karriere/arbeitsleben/heiko-mell/
    language: de-DE
    ttl: 360
    time_zone: UTC
- domain: kinocheck.de
  name: filmstarts
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://kinocheck.de/filmstarts
    time_zone: Europe/Berlin
    ttl: 1440
    language: de
- domain: newyorker.com
  name: magazine
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.newyorker.com/magazine
    language: en
    ttl: 360
    time_zone: UTC
- domain: nomanssky.com
  name: news
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.nomanssky.com/news/
    language: en-GB
    ttl: 360
    time_zone: UTC
- domain: pankow.lebensmittel-kontrollergebnisse.de
  name: search
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://pankow.lebensmittel-kontrollergebnisse.de/Search
    language: de
    ttl: 360
    time_zone: Europe/Berlin
- domain: phys.org
  name: weekly
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://phys.org/weekly-news/
    time_zone: Europe/London
    ttl: 1440
- domain: rbb24.de
  name: meistgeklickt
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    title: 'rbb24.de: meistgeklickt'
    url: https://rbb24.de/
    time_zone: Europe/Berlin
    ttl: 30
    language: de
- domain: robinwood.de
  name: aktuelles
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.robinwood.de/was-gibt-es-neues/aktuelles
    time_zone: Europe/Berlin
    ttl: 720
    language: de
- domain: s3.amazonaws.com
  name: popular_movies
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://s3.amazonaws.com/popular-movies/movies.json
    time_zone: UTC
    ttl: 1440
    json: true
- domain: sebastianvettel.de
  name: news
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://sebastianvettel.de/news/
    language: de-DE
    ttl: 8640
    time_zone: Europe/Berlin
- domain: softwareleadweekly.com
  name: issues
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://softwareleadweekly.com/issues
    time_zone: UTC
    ttl: 720
- domain: solarthermalworld.org
  name: news
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://solarthermalworld.org/news
    time_zone: UTC
    ttl: 180
- domain: spektrum.de
  name: meistgelesen
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    title: 'spektrum.de: meistgelesen'
    url: https://www.spektrum.de/
    time_zone: Europe/Berlin
    ttl: 60
    language: de
- domain: spiegel.de
  name: impressum_autor
  valid_channel_url: false
  url_parameters:
    id: *1
  default_parameters:
    id: 975b6ae0-0001-0003-0000-000000018282
  channel:
    url: https://www.spiegel.de/impressum/autor-%<id>s
    time_zone: Europe/Berlin
    ttl: 180
    language: de
- domain: stackoverflow.com
  name: hot_network_questions
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    title: 'stackoverflow.com: Hot Network Questions'
    url: https://stackoverflow.com/questions
    time_zone: America/New_York
    ttl: 30
- domain: steuerzahler.de
  name: news
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.steuerzahler.de/news
    time_zone: Europe/Berlin
    ttl: 720
    language: de
- domain: stripes.com
  name: index
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.stripes.com/
    language: en
    ttl: 360
    time_zone: America/New_York
- domain: support.apple.com
  name: en_gb_ht201222
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://support.apple.com/en-gb/HT201222
    language: en
    ttl: 360
    time_zone: UTC
- domain: support.apple.com
  name: exchange_repair
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://support.apple.com/exchange_repair
    time_zone: America/Los_Angeles
    ttl: 720
- domain: teneriffa-news.com
  name: news
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.teneriffa-news.com/news
    time_zone: Europe/Lisbon
    ttl: 720
    language: de
- domain: test.de
  name: archiv
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.test.de/archiv/
    language: de
    ttl: 360
    time_zone: Europe/Berlin
- domain: theguardian.com
  name: international_mostpopular
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    title: 'theguardian.com: International most popular'
    url: https://www.theguardian.com/international
    time_zone: Europe/London
    ttl: 60
- domain: thoughtworks.com
  name: insights
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.thoughtworks.com/insights
    language: en
    ttl: 360
    time_zone: UTC
- domain: tourismusnetzwerk-brandenburg.de
  name: aktuelle_nachrichten
  valid_channel_url: true
  url_parameters: {}
  default_parameters: {}
  channel:
    url: https://www.tourismusnetzwerk-brandenburg.de/nc/aktuelle-nachrichten/
    time_zone: Europe/Berlin
    ttl: 720
    language: de
- domain: webentwickler-jobs.de
  name: in
  valid_channel_url: false
  url_parameters:
    region: *1
  default_parameters:
    region: berlin
  channel:
    url: https://www.webentwickler-jobs.de/in/%<region>s
    language: de
    ttl: 360
    time_zone: Europe/Berlin
